# Generated by Django 2.0 on 2021-02-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, max_length=100, null=True)),
                ('report_type', models.CharField(blank=True, choices=[(1, 'Sampling'), (2, 'Bulk Order')], max_length=100, null=True)),
            ],
        ),
    ]
