# Generated by Django 2.0 on 2021-03-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Sampling', 'Sampling'), ('Bulk Order', 'Bulk Order')], max_length=100, null=True),
        ),
    ]
