# Generated by Django 2.0 on 2020-12-30 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('time_status', models.CharField(blank=True, max_length=100, null=True)),
                ('c_status', models.CharField(blank=True, max_length=100, null=True)),
                ('print_tech', models.CharField(blank=True, max_length=100, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('qunt', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('gmt_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('del_date', models.DateField(blank=True, null=True)),
                ('dupl_del_date', models.CharField(blank=True, max_length=100, null=True)),
                ('dos', models.DateField(blank=True, null=True)),
                ('doe', models.DateField(blank=True, null=True)),
                ('bpm', models.CharField(blank=True, max_length=100, null=True)),
                ('pid', models.IntegerField(blank=True, default=0, null=True)),
                ('bpmstatus', models.CharField(blank=True, max_length=100, null=True)),
                ('gre_date', models.DateField(blank=True, null=True)),
                ('print_date', models.DateField(blank=True, null=True)),
                ('checking_date', models.DateField(blank=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bulk_Printed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_date', models.DateField(blank=True, null=True)),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Bulk_Order')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('additional_email', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courier_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('awb_no', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('rep_date', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('c_date', models.DateField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('tr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('d_date', models.DateField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='')),
                ('c_date', models.DateField(blank=True, null=True)),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Bulk_Order')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric_Cheking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_reject', models.CharField(blank=True, max_length=100, null=True)),
                ('f_date', models.DateField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='')),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Bulk_Order')),
            ],
        ),
        migrations.CreateModel(
            name='FirstBulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('f_date', models.DateField(blank=True, null=True)),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Bulk_Order')),
            ],
        ),
        migrations.CreateModel(
            name='FPT_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_no', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='')),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Bulk_Order')),
            ],
        ),
        migrations.CreateModel(
            name='GMT_Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Griege_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_date', models.DateField(blank=True, null=True)),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Bulk_Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('p_date', models.DateField(blank=True, null=True)),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Bulk_Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('construction', models.CharField(blank=True, max_length=100, null=True)),
                ('gsm', models.CharField(blank=True, max_length=100, null=True)),
                ('weave', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('moq', models.CharField(blank=True, max_length=100, null=True)),
                ('leadtime', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('solid_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('printed_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_rate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('additional_email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status1', models.CharField(blank=True, max_length=100, null=True)),
                ('c_status', models.CharField(blank=True, max_length=100, null=True)),
                ('time_status', models.CharField(blank=True, max_length=100, null=True)),
                ('time_status2', models.CharField(blank=True, max_length=100, null=True)),
                ('c_table', models.CharField(blank=True, max_length=100, null=True)),
                ('status_buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('awb_no', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_message', models.CharField(blank=True, max_length=800, null=True)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('dos', models.DateField(blank=True, null=True)),
                ('doe', models.DateField(blank=True, null=True)),
                ('timetaken', models.CharField(blank=True, max_length=100, null=True)),
                ('del_date', models.DateField(blank=True, null=True)),
                ('first', models.DateField(blank=True, null=True)),
                ('second', models.DateField(blank=True, null=True)),
                ('third', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('technique', models.CharField(blank=True, choices=[('Solid', 'Solid'), ('Rotary', 'Rotary'), ('Digital', 'Digital'), ('Yarn Dyed', 'Yarn Dyed'), ('Adhoc', 'Adhoc')], max_length=100, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Drop')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Product')),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM')),
            ],
        ),
        migrations.CreateModel(
            name='Search_for_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('additional_email', models.TextField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpToDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sampling',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Season'),
        ),
        migrations.AddField(
            model_name='sampling',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='rm',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Status'),
        ),
        migrations.AddField(
            model_name='rm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gmt_vendor',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Status'),
        ),
        migrations.AddField(
            model_name='gmt_vendor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch_detail',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Drop'),
        ),
        migrations.AddField(
            model_name='dispatch_detail',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Season'),
        ),
        migrations.AddField(
            model_name='dispatch_detail',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='courier_detail',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Sampling'),
        ),
        migrations.AddField(
            model_name='courier_detail',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='bulk_order',
            name='buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='bulk_order',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Drop'),
        ),
        migrations.AddField(
            model_name='bulk_order',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Sampling'),
        ),
        migrations.AddField(
            model_name='bulk_order',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Season'),
        ),
        migrations.AddField(
            model_name='bulk_order',
            name='sup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
    ]
