# Generated by Django 2.0 on 2020-12-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_sample', models.CharField(blank=True, max_length=100, null=True)),
                ('t_bulk', models.CharField(blank=True, max_length=100, null=True)),
                ('t_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('t_dispatch', models.CharField(blank=True, max_length=100, null=True)),
                ('t_dispatch_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='SummarySupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_sample', models.CharField(blank=True, max_length=100, null=True)),
                ('t_bulk', models.CharField(blank=True, max_length=100, null=True)),
                ('t_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('t_dispatch', models.CharField(blank=True, max_length=100, null=True)),
                ('t_dispatch_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier')),
            ],
        ),
    ]
