# Generated by Django 2.0 on 2021-01-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_summarybuyer_summarysupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_detail',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
    ]
