# Generated by Django 2.0 on 2021-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_dispatch_detail_gmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='update_perm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
