# Generated by Django 2.0 on 2021-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_supplier_update_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampling',
            name='time_in_approve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='time_in_develop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
