# Generated by Django 2.0 on 2021-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20210122_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampling',
            name='time_in_approve',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='time_in_develop',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
