# Generated by Django 2.0 on 2021-02-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_auto_20210122_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gmt_vendor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sampling',
            name='time_status',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='image',
        ),
    ]
