# Generated by Django 2.0 on 2021-03-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0007_auto_20210204_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk_order',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulk_order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulk_printed',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulk_printed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier_detail',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier_detail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch_detail',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch_detail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drop',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drop',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabric_cheking',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabric_cheking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firstbulk',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firstbulk',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fpt_status',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpt_status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gmt_vendor',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='griege_status',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='griege_status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment_status',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rm',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampling',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summarybuyer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summarybuyer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summarysupplier',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summarysupplier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uptodate',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
