# Generated by Django 2.0 on 2021-03-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_auto_20210312_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk_order',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='bulk_printed',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='bulk_printed',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
        migrations.AddField(
            model_name='bulk_printed',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='bulk_printed',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='dispatch_detail',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='fabric_cheking',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='fabric_cheking',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
        migrations.AddField(
            model_name='fabric_cheking',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='fabric_cheking',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='firstbulk',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='firstbulk',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
        migrations.AddField(
            model_name='firstbulk',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='firstbulk',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='fpt_status',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='fpt_status',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
        migrations.AddField(
            model_name='fpt_status',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='fpt_status',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='griege_status',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='griege_status',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
        migrations.AddField(
            model_name='griege_status',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='griege_status',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='payment_status',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='payment_status',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
        migrations.AddField(
            model_name='payment_status',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='payment_status',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='summarybuyer',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
        migrations.AddField(
            model_name='summarybuyer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Supplier'),
        ),
        migrations.AddField(
            model_name='summarysupplier',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Buyer'),
        ),
        migrations.AddField(
            model_name='summarysupplier',
            name='gmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.GMT_Vendor'),
        ),
        migrations.AddField(
            model_name='summarysupplier',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.RM'),
        ),
    ]
